pub const PUNCTS: &[(&str, super::token::TokenKind)] = &[
    ("Tune", T![OEq]),
    ("CloseTune", T![CEq]),
    ("Boost", T![OAdd]),
    ("CloseBoost", T![CAdd]),
    ("Drain", T![OSub]),
    ("CloseDrain", T![CSub]),
    ("Amplify", T![OMul]),
    ("CloseAmplify", T![CMul]),
    ("Disperse", T![ODiv]),
    ("CloseDisperse", T![CDiv]),
    ("Salvage", T![OMod]),
    ("CloseSalvage", T![CMod]),
    ("-", T![Not]),
    ("<", T![OGen]),
    (">", T![CGen]),
    ("Beacon", T![Beacon]),
    ("Retrieve", T![Retrieve]),
];

pub const KEYWORDS: &[(&str, super::token::TokenKind)] = &[
    ("Execute order", T![OFnCall]),
    ("Order executed", T![CFnCall]),
    ("A long time ago in a", T![OFnDecl1]),
    ("far, far away...", T![OFnDecl2]),
    ("May the force be with you.", T![CFnDecl]),
    ("Do, or do not. There is no try.", T![If]),
    ("These aren't the droids you're looking for.", T![Else]),
    ("You have failed me for the last time.", T![IfEnd]),
    ("I am your father.", T![Assign]),
    ("Judge me by my size, do you ?", T![Assign]),
    ("Who, mesa ?", T![Assign]),
    ("What a piece of junk!", T![OAssign]),
    ("The garbage will do.", T![CAssign]),
    ("I am a big deal in the resistance.", T![Let]),
    ("The force is strong with this one.", T![Let]),
    ("That's one hell of a pilot.", T![Let]),
    ("From a certain point of view.", T![True]),
    ("That's impossible!", T![False]),
    ("Starfield", T![Variadic]),
    ("Hypersignal", T![OExtrnFn]),
    ("Jamsignal", T![CExtrnFn]),
    ("Manifest", T![OFnParams]),
    ("CloseManifest", T![CFnParams]),
    ("UnloadCargo", T![OFnCallReturn]),
    ("CargoDock", T![OFnReturn]),
    ("CloseCargo", T![CFnReturn]),
];

pub const TYPES: &[(&str, super::token::TokenKind)] = &[
    ("Credit", T![TyInt]),
    ("Holotext", T![TyStr]),
    ("Signal", T![TyBool]),
    ("Target", T![TyPtr]),
];
